services:
  product-service:
    image: product-service-image:latest
    build:
      context: .  # Sets current directory for Dockerfile
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/product-service
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy # Wait for mongo to start
    volumes:
      - product-service-data:/app/data


  mongo:
    image: mongo:5.0.28
    restart: always
    ports:
      - "27017:27017"
    healthcheck: # Condition for product-service: service_healthy
      test: [ "CMD", "mongo", "--eval", "db.adminCommand({ ping: 1 })" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s # time for recovery
    volumes:
      - ./mongo-data:/data/db



volumes:
  mongo-data:
  product-service-data: