services:
  postgres-db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_pass
      - POSTGRES_DB=order_db
    ports:
      - "5432:5432"

volumes:
  postgres-data: