services:
  order-service:
    image: order-service-image:latest
    build:
      context: .  # Sets current directory for Dockerfile
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgres-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=order_user
      - SPRING_DATASOURCE_PASSWORD=order_pass
    ports:
      - "8081:8081"
    depends_on:
      order-postgres-db:
        condition: service_healthy # Wait for postgres to start
    volumes:
      - order-service-data:/app/data

  order-postgres-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_pass
    ports:
      - "5433:5432"
    healthcheck: # Condition for order-service: service_healthy
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  order-service-data: