services:
  inventory-service:
    image: inventory-service:latest
    build:
      context: .  # Sets current directory for Dockerfile
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-postgres-db:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=inventory_user
      - SPRING_DATASOURCE_PASSWORD=inventory_pass
    ports:
      - "8082:8082"
    depends_on:
      inventory-postgres-db:
        condition: service_healthy # Wait for postgres to start
    volumes:
      - inventory-service-data:/app/data

  inventory-postgres-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data




volumes:
  postgres-data:
  inventory-service-data: